openapi: 3.0.0
info:
  title: Sample API
  description: This is a sample API
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/porterd56/sample/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /users/{userId}:
    get:
      summary: Returns a user by ID
      operationId: users_user_id_get
      parameters:
      - name: userId
        in: path
        description: The ID of the user to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: The specified user ID is invalid (e.g. not a number)
        "404":
          description: A user with the specified ID was not found
      x-openapi-router-controller: swagger_server.myControllers.default_controller
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      example:
        name: name
        id: 0

